"""create users table

Revision ID: 01b5125e4f4f
Revises: 
Create Date: 2026-06-03 22:51:11.456945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b5125e4f4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('hashed_pin', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('SUPER_USER', 'BRANCH_SUPERVISOR', 'OFFICE_ADMIN', 'INSTRUCTOR', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'BLOCKED', 'DEACTIVATED', name='userstatus'), nullable=False),
    sa.Column('created_by_phone', sa.String(length=20), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('pin_reset_otp', sa.String(length=6), nullable=True),
    sa.Column('pin_reset_otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_phone'], ['users.phone'], ),
    sa.PrimaryKeyConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
