"""add_can_backdate_document_date

Revision ID: 0cedeb757155
Revises: cc4d1dfb0f04
Create Date: 2026-07-08 10:59:02.771742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cedeb757155'
down_revision: Union[str, None] = 'cc4d1dfb0f04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('document_date', sa.Date(), nullable=True))
    op.add_column('payments', sa.Column('document_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('can_backdate', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_backdate')
    op.drop_column('payments', 'document_date')
    op.drop_column('consultations', 'document_date')
    # ### end Alembic commands ###
