"""add_purchased_theory_sessions

Revision ID: 122158b1ace5
Revises: o4p5q6r7s8t9u
Create Date: 2026-08-14 17:26:47.118946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '122158b1ace5'
down_revision: Union[str, None] = 'o4p5q6r7s8t9u'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_lesson_plans', sa.Column('purchased_theory_sessions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_lesson_plans', 'purchased_theory_sessions')
    # ### end Alembic commands ###
