"""add commissions and fuel tracking tables

Revision ID: 7fdead775930
Revises: 280fdeff609d
Create Date: 2026-07-12 12:06:06.633764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fdead775930'
down_revision: Union[str, None] = '280fdeff609d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('lesson_type', sa.String(length=50), nullable=True),
    sa.Column('transmission_type', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_rates_company_id'), 'commission_rates', ['company_id'], unique=False)
    op.create_table('fuel_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('rate_per_lesson', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('effective_from', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_rates_company_id'), 'fuel_rates', ['company_id'], unique=False)
    op.create_index(op.f('ix_fuel_rates_vehicle_id'), 'fuel_rates', ['vehicle_id'], unique=False)
    op.create_table('fuel_refuelings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('fuel_rate_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('liters', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('lessons_covered', sa.Integer(), nullable=False),
    sa.Column('refueled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('odometer_reading', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['fuel_rate_id'], ['fuel_rates.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuel_refuelings_company_id'), 'fuel_refuelings', ['company_id'], unique=False)
    op.create_index(op.f('ix_fuel_refuelings_vehicle_id'), 'fuel_refuelings', ['vehicle_id'], unique=False)
    op.create_table('commissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.String(length=20), nullable=False),
    sa.Column('client_lesson_id', sa.UUID(), nullable=True),
    sa.Column('training_session_id', sa.UUID(), nullable=True),
    sa.Column('commission_rate_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'paid', name='commissionstatus'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_by', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_lesson_id'], ['client_lessons.id'], ),
    sa.ForeignKeyConstraint(['commission_rate_id'], ['commission_rates.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.phone'], ),
    sa.ForeignKeyConstraint(['paid_by'], ['users.phone'], ),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_client_lesson_id'), 'commissions', ['client_lesson_id'], unique=False)
    op.create_index(op.f('ix_commissions_company_id'), 'commissions', ['company_id'], unique=False)
    op.create_index(op.f('ix_commissions_instructor_id'), 'commissions', ['instructor_id'], unique=False)
    op.create_index(op.f('ix_commissions_training_session_id'), 'commissions', ['training_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commissions_training_session_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_instructor_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_company_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_client_lesson_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_fuel_refuelings_vehicle_id'), table_name='fuel_refuelings')
    op.drop_index(op.f('ix_fuel_refuelings_company_id'), table_name='fuel_refuelings')
    op.drop_table('fuel_refuelings')
    op.drop_index(op.f('ix_fuel_rates_vehicle_id'), table_name='fuel_rates')
    op.drop_index(op.f('ix_fuel_rates_company_id'), table_name='fuel_rates')
    op.drop_table('fuel_rates')
    op.drop_index(op.f('ix_commission_rates_company_id'), table_name='commission_rates')
    op.drop_table('commission_rates')
    # ### end Alembic commands ###
