"""cart_items, follow_up_cart_items junction, follow_up_type

Revision ID: 87e957604ba6
Revises: c8941a4992d6
Create Date: 2026-06-14 08:53:23.036053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87e957604ba6'
down_revision: Union[str, None] = 'c8941a4992d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


followuptype = postgresql.ENUM('conversion', 'payment', name='followuptype', create_type=True)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    followuptype.create(op.get_bind())
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('consultation_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('interested', 'consulting', 'converted', 'lost', name='cartitemstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_items_consultation_id'), 'cart_items', ['consultation_id'], unique=False)
    op.create_table('follow_up_cart_items',
    sa.Column('follow_up_id', sa.UUID(), nullable=False),
    sa.Column('cart_item_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cart_item_id'], ['cart_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follow_up_id'], ['follow_ups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follow_up_id', 'cart_item_id')
    )
    op.alter_column('consultations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('consultations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('follow_ups', sa.Column('type', followuptype, nullable=True))
    op.execute("UPDATE follow_ups SET type = 'conversion' WHERE type IS NULL")
    op.alter_column('follow_ups', 'type', nullable=False)
    op.alter_column('follow_ups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('follow_ups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('follow_ups', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('follow_ups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('follow_ups', 'type')
    op.alter_column('consultations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('consultations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table('follow_up_cart_items')
    op.drop_index(op.f('ix_cart_items_consultation_id'), table_name='cart_items')
    op.drop_table('cart_items')
    followuptype.drop(op.get_bind())
    # ### end Alembic commands ###
