"""add_company_id_to_schedule_breaks

Revision ID: 89c43e2abb60
Revises: 0cedeb757155
Create Date: 2026-07-10 17:49:44.954482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c43e2abb60'
down_revision: Union[str, None] = '0cedeb757155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DEFAULT_COMPANY_ID = "00000000-0000-0000-0000-000000000001"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_breaks', sa.Column('company_id', sa.UUID(), nullable=True))
    # Backfill existing records with the default company ID
    op.execute(f"UPDATE schedule_breaks SET company_id = '{DEFAULT_COMPANY_ID}' WHERE company_id IS NULL")
    op.alter_column('schedule_breaks', 'company_id', nullable=False)
    op.create_index(op.f('ix_schedule_breaks_company_id'), 'schedule_breaks', ['company_id'], unique=False)
    op.create_foreign_key(None, 'schedule_breaks', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schedule_breaks', type_='foreignkey')
    op.drop_index(op.f('ix_schedule_breaks_company_id'), table_name='schedule_breaks')
    op.drop_column('schedule_breaks', 'company_id')
    # ### end Alembic commands ###
