"""add_paid_by_paid_at_to_expenses

Revision ID: 8bde55b2c718
Revises: ee2cd2f573fd
Create Date: 2026-07-07 13:41:17.337032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bde55b2c718'
down_revision: Union[str, None] = 'ee2cd2f573fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('paid_by', sa.String(length=20), nullable=True))
    op.add_column('expenses', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'expenses', 'users', ['paid_by'], ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'paid_at')
    op.drop_column('expenses', 'paid_by')
    # ### end Alembic commands ###
