"""add_cancelled_columns_to_payments

Revision ID: 8d17fe1c8a04
Revises: 8525eac07110
Create Date: 2026-08-14 12:34:49.151069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d17fe1c8a04'
down_revision: Union[str, None] = '8525eac07110'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
