"""add_vehicle_schedule_slots

Revision ID: 9e593e98e7ad
Revises: 125cb166c0d6
Create Date: 2026-07-06 17:04:11.742924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e593e98e7ad'
down_revision: Union[str, None] = '125cb166c0d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = "c3d4e5f6a7b8"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_schedule_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('instructor_id', sa.String(length=20), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_schedule_slots_vehicle_id'), 'vehicle_schedule_slots', ['vehicle_id'], unique=False)
    op.create_index('ix_vss_vehicle_day_time', 'vehicle_schedule_slots', ['vehicle_id', 'day_of_week', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vss_vehicle_day_time', table_name='vehicle_schedule_slots')
    op.drop_index(op.f('ix_vehicle_schedule_slots_vehicle_id'), table_name='vehicle_schedule_slots')
    op.drop_table('vehicle_schedule_slots')
    # ### end Alembic commands ###
