"""add recovery_reason to cart_items

Revision ID: af1e9a7e0fad
Revises: 87e957604ba6
Create Date: 2026-06-14 12:18:02.232782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1e9a7e0fad'
down_revision: Union[str, None] = '87e957604ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('recovery_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_items', 'recovery_reason')
    # ### end Alembic commands ###
