"""add_created_by_phone_to_payments

Revision ID: cc4d1dfb0f04
Revises: 8bde55b2c718
Create Date: 2026-07-08 10:44:05.459663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc4d1dfb0f04'
down_revision: Union[str, None] = '8bde55b2c718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_by_phone', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_payments_created_by_phone'), 'payments', ['created_by_phone'], unique=False)
    op.create_foreign_key(None, 'payments', 'users', ['created_by_phone'], ['phone'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_created_by_phone'), table_name='payments')
    op.drop_column('payments', 'created_by_phone')
    # ### end Alembic commands ###
