"""add discounts

Revision ID: d13cd90a16c4
Revises: d4c12b2e7a15
Create Date: 2026-08-15 09:08:30.935644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd13cd90a16c4'
down_revision: Union[str, None] = 'd4c12b2e7a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.Enum('fixed', 'percentage', name='discounttype'), nullable=False),
    sa.Column('discount_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applies_to', sa.Enum('all', 'product', 'package', name='discountappliesto'), nullable=False),
    sa.Column('product_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('package_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending', 'approved', 'rejected', 'expired', name='discountstatus'), nullable=False),
    sa.Column('requested_by', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=20), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.phone'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.phone'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='uq_discount_company_code')
    )
    op.create_index(op.f('ix_discounts_branch_id'), 'discounts', ['branch_id'], unique=False)
    op.create_index(op.f('ix_discounts_code'), 'discounts', ['code'], unique=False)
    op.create_index(op.f('ix_discounts_company_id'), 'discounts', ['company_id'], unique=False)
    op.create_index(op.f('ix_discounts_requested_by'), 'discounts', ['requested_by'], unique=False)
    op.create_table('cart_item_discounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cart_item_id', sa.UUID(), nullable=False),
    sa.Column('discount_id', sa.UUID(), nullable=False),
    sa.Column('applied_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('applied_by', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_by'], ['users.phone'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cart_item_id'], ['cart_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discount_id'], ['discounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_item_discounts_cart_item_id'), 'cart_item_discounts', ['cart_item_id'], unique=False)
    op.create_index(op.f('ix_cart_item_discounts_discount_id'), 'cart_item_discounts', ['discount_id'], unique=False)

    # Backfill discount permissions for existing companies based on the new defaults.
    role_permissions = [
        ("company_super_user", "discounts.manage"),
        ("office_admin", "discounts.view"),
        ("office_admin", "discounts.create"),
        ("office_admin", "discounts.edit"),
        ("office_admin", "discounts.apply"),
        ("branch_supervisor", "discounts.view"),
        ("branch_supervisor", "discounts.create"),
        ("branch_supervisor", "discounts.edit"),
        ("branch_supervisor", "discounts.apply"),
        ("manager", "discounts.view"),
        ("manager", "discounts.create"),
        ("manager", "discounts.edit"),
        ("manager", "discounts.apply"),
        ("manager", "discounts.approve"),
        ("manager", "discounts.reject"),
        ("supervisor", "discounts.view"),
        ("supervisor", "discounts.create"),
        ("supervisor", "discounts.edit"),
        ("supervisor", "discounts.apply"),
        ("supervisor", "discounts.approve"),
        ("supervisor", "discounts.reject"),
        ("reception", "discounts.view"),
        ("instructor", "discounts.view"),
    ]
    for role, permission in role_permissions:
        op.execute(
            sa.text(
                """
                INSERT INTO role_permissions (company_id, role, permission)
                SELECT id, :role, :permission
                FROM companies
                WHERE NOT EXISTS (
                    SELECT 1 FROM role_permissions rp
                    WHERE rp.company_id = companies.id AND rp.role = :role AND rp.permission = :permission
                )
                """
            ).bindparams(role=role, permission=permission)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_item_discounts_discount_id'), table_name='cart_item_discounts')
    op.drop_index(op.f('ix_cart_item_discounts_cart_item_id'), table_name='cart_item_discounts')
    op.drop_table('cart_item_discounts')
    op.drop_index(op.f('ix_discounts_requested_by'), table_name='discounts')
    op.drop_index(op.f('ix_discounts_company_id'), table_name='discounts')
    op.drop_index(op.f('ix_discounts_code'), table_name='discounts')
    op.drop_index(op.f('ix_discounts_branch_id'), table_name='discounts')
    op.drop_table('discounts')
    op.execute(sa.text("DELETE FROM role_permissions WHERE permission LIKE 'discounts.%'"))
    # ### end Alembic commands ###
