"""add total_paid and balance to payments

Revision ID: e07e7f5b5c50
Revises: fd36e62dd528
Create Date: 2026-06-21 13:35:57.687820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07e7f5b5c50'
down_revision: Union[str, None] = 'fd36e62dd528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('total_paid', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    op.add_column('payments', sa.Column('balance', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'balance')
    op.drop_column('payments', 'total_paid')
    # ### end Alembic commands ###
