"""add_vehicle_id_to_expenses

Revision ID: e713417c4b28
Revises: 4a3ed1ce60df
Create Date: 2026-07-07 12:24:00.156483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e713417c4b28'
down_revision: Union[str, None] = '4a3ed1ce60df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('vehicle_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_expenses_vehicle_id'), 'expenses', ['vehicle_id'], unique=False)
    op.create_foreign_key(None, 'expenses', 'vehicles', ['vehicle_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_index(op.f('ix_expenses_vehicle_id'), table_name='expenses')
    op.drop_column('expenses', 'vehicle_id')
    # ### end Alembic commands ###
