"""add receipt fields to payments

Revision ID: edf1f5deb926
Revises: a47cfe4be574
Create Date: 2026-06-14 13:12:57.556372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edf1f5deb926'
down_revision: Union[str, None] = 'a47cfe4be574'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('receipt_number', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('system_receipt_number', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'payments', ['system_receipt_number'])
    op.create_unique_constraint(None, 'payments', ['receipt_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_column('payments', 'system_receipt_number')
    op.drop_column('payments', 'receipt_number')
    # ### end Alembic commands ###
